on:
  schedule:
    - cron: '00 03 * * SAT'

name: Scheduled Actions
jobs:
    action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: create-issue-svn
              uses: ./.github/actions/issue-maker
              with:
                repo-token: ${{secrets.GITHUB_TOKEN}}
                issue-title: "Enviar arquivos para SVN"
                issue-body: "Enviar arquivos para SVN"
            - name: create-issue-blog
              uses: ./.github/actions/issue-maker
              with:
                repo-token: ${{secrets.GITHUB_TOKEN}}
                issue-title: "Escrever relat贸rio semanal no blog"
                issue-body: "Escrever relat贸rio semanal no blog"


name: Scheduled Actions
jobs:
    action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: create-issue-svn
              uses: ./.github/actions/issue-maker
              with:
                repo-token: ${{secrets.GITHUB_TOKEN}}
                issue-title: "Enviar arquivos para SVN"
                issue-body: "Enviar arquivos para SVN"
            - name: create-issue-blog
              uses: ./.github/actions/issue-maker
              with:
                repo-token: ${{secrets.GITHUB_TOKEN}}
                issue-title: "Escrever relat贸rio semanal no blog"
                issue-body: "Escrever relat贸rio semanal no blog"
